version: '2'

services:
  db:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
      - MYSQL_DATABASE=sportorezka_db
    ports:
      - '3306:3306'
    volumes:
      - .docker/mysql_data:/var/lib/mysql
      - .docker/mysql_conf:/etc/mysql/conf.d
  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    environment:
      - PMA_USER=db_user
      - PMA_PASSWORD=db_password
    depends_on:
      - db
    ports:
      - '8080:80'
